dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/44403.dot -o data/CHEBI/png_files_reduit/graphes_coins/44403.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/21656.dot -o data/CHEBI/png_files_reduit/graphes_coins/21656.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/51832.dot -o data/CHEBI/png_files_reduit/graphes_coins/51832.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/24023.dot -o data/CHEBI/png_files_reduit/graphes_coins/24023.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/29900.dot -o data/CHEBI/png_files_reduit/graphes_coins/29900.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/12056.dot -o data/CHEBI/png_files_reduit/graphes_coins/12056.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/26910.dot -o data/CHEBI/png_files_reduit/graphes_coins/26910.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/13513.dot -o data/CHEBI/png_files_reduit/graphes_coins/13513.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/41854.dot -o data/CHEBI/png_files_reduit/graphes_coins/41854.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/44403.dot -o data/CHEBI/png_files_reduit/graphes_coins/44403.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/21656.dot -o data/CHEBI/png_files_reduit/graphes_coins/21656.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/51832.dot -o data/CHEBI/png_files_reduit/graphes_coins/51832.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/24023.dot -o data/CHEBI/png_files_reduit/graphes_coins/24023.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/29900.dot -o data/CHEBI/png_files_reduit/graphes_coins/29900.png
dot -Tpng data/CHEBI/dot_files_reduit/graphes_coins/12056.dot -o data/CHEBI/png_files_reduit/graphes_coins/12056.png
